// Command genabi generates internal/abi/consts.go: the wasi-libc constant
// values (errno, poll, socket, fcntl and signal numbers) the host must use
// when talking to the guest. It asks the wasi-sdk C preprocessor, through
// the same wasm/libpgzero/include wrapper headers the guest is built with, so the
// two sides cannot drift apart.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"strconv"
	"strings"
)

var groups = []struct {
	comment string
	names   []string
}{
	{"errno values", strings.Fields(`EPERM ENOENT ESRCH EINTR EIO EBADF ECHILD EAGAIN ENOMEM EACCES
		EFAULT EEXIST ENOTDIR EISDIR EINVAL ENFILE EMFILE ENOSPC ESPIPE EPIPE ERANGE ENOSYS
		ENOTSOCK EDESTADDRREQ EMSGSIZE EPROTOTYPE ENOPROTOOPT EPROTONOSUPPORT EOPNOTSUPP
		EAFNOSUPPORT EADDRINUSE EADDRNOTAVAIL ENETDOWN ENETUNREACH ECONNABORTED ECONNRESET
		ENOBUFS EISCONN ENOTCONN ETIMEDOUT ECONNREFUSED EHOSTUNREACH EALREADY EINPROGRESS`)},
	{"poll events", strings.Fields(`POLLIN POLLOUT POLLERR POLLHUP POLLNVAL POLLPRI POLLRDNORM POLLWRNORM`)},
	{"socket domains, types and flags", strings.Fields(`AF_UNSPEC AF_INET AF_INET6 AF_UNIX
		SOCK_STREAM SOCK_DGRAM SOCK_NONBLOCK SOCK_CLOEXEC SHUT_RD SHUT_WR SHUT_RDWR
		MSG_PEEK MSG_DONTWAIT MSG_NOSIGNAL`)},
	{"socket options", strings.Fields(`SOL_SOCKET SO_REUSEADDR SO_KEEPALIVE SO_ERROR SO_RCVBUF
		SO_SNDBUF SO_TYPE SO_LINGER IPPROTO_TCP IPPROTO_IPV6 IPV6_V6ONLY TCP_NODELAY
		TCP_KEEPIDLE TCP_KEEPINTVL TCP_KEEPCNT`)},
	{"fcntl", strings.Fields(`O_CREAT O_EXCL O_TRUNC O_RDWR O_NONBLOCK O_CLOEXEC F_GETFD F_SETFD F_GETFL F_SETFL F_DUPFD
		F_DUPFD_CLOEXEC FD_CLOEXEC`)},
	{"signals", strings.Fields(`SIGHUP SIGINT SIGQUIT SIGILL SIGTRAP SIGABRT SIGBUS SIGFPE SIGKILL
		SIGUSR1 SIGSEGV SIGUSR2 SIGPIPE SIGALRM SIGTERM SIGCHLD SIGCONT SIGSTOP SIGTSTP SIGTTIN
		SIGTTOU SIGURG SIGXCPU SIGXFSZ SIGVTALRM SIGPROF SIGWINCH SIGIO SIGSYS NSIG`)},
	{"wait", strings.Fields(`WNOHANG`)},
}

func main() {
	sdk := os.Getenv("WASI_SDK")
	if sdk == "" {
		sdk = ".tools/wasi-sdk"
	}
	var probe bytes.Buffer
	for _, h := range []string{"errno.h", "poll.h", "fcntl.h", "signal.h", "sys/socket.h",
		"sys/wait.h", "netinet/in.h", "netinet/tcp.h"} {
		fmt.Fprintf(&probe, "#include <%s>\n", h)
	}
	for _, g := range groups {
		for _, n := range g.names {
			fmt.Fprintf(&probe, "@@\"%s\" %s\n", n, n)
		}
	}
	cmd := exec.Command(sdk+"/bin/clang", "--target=wasm32-wasip2", "-isystem", "wasm/libpgzero/include",
		"-D_WASI_EMULATED_PROCESS_CLOCKS", "-D_WASI_EMULATED_GETPID", "-E", "-P", "-")
	cmd.Stdin = &probe
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		log.Fatalf("preprocess: %v", err)
	}
	values := map[string]int64{}
	for _, line := range strings.Split(string(out), "\n") {
		if !strings.HasPrefix(line, "@@") {
			continue
		}
		name, expr, _ := strings.Cut(strings.TrimPrefix(line, "@@"), " ")
		name = strings.Trim(name, `"`)
		if expr == name {
			continue // not defined by wasi-libc
		}
		v, err := eval(expr)
		if err != nil {
			log.Fatalf("%s: cannot evaluate %q: %v", name, expr, err)
		}
		values[name] = v
	}

	var src bytes.Buffer
	src.WriteString("// Code generated by wasm/cmd/genabi from wasi-libc headers. DO NOT EDIT.\n\n")
	src.WriteString("package abi\n\n")
	for _, g := range groups {
		fmt.Fprintf(&src, "// %s\nconst (\n", g.comment)
		var missing []string
		for _, n := range g.names {
			v, ok := values[n]
			if !ok {
				missing = append(missing, n)
				continue
			}
			fmt.Fprintf(&src, "\t%s = %d\n", n, v)
		}
		src.WriteString(")\n\n")
		if len(missing) > 0 {
			fmt.Fprintf(&src, "// Not defined by wasi-libc: %s\n\n", strings.Join(missing, ", "))
		}
	}
	formatted, err := format.Source(src.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("internal/abi/consts.go", formatted, 0o644); err != nil {
		log.Fatal(err)
	}
}

// eval evaluates the simple constant expressions wasi-libc's macros expand
// to: parenthesized integer literals, possibly shifted, OR'ed together or
// negated.
func eval(expr string) (int64, error) {
	expr = strings.TrimSpace(expr)
	for strings.HasPrefix(expr, "(") && strings.HasSuffix(expr, ")") && balanced(expr[1:len(expr)-1]) {
		expr = strings.TrimSpace(expr[1 : len(expr)-1])
	}
	if parts := splitTop(expr, '|'); len(parts) > 1 {
		var v int64
		for _, p := range parts {
			pv, err := eval(p)
			if err != nil {
				return 0, err
			}
			v |= pv
		}
		return v, nil
	}
	if l, r, ok := strings.Cut(expr, "<<"); ok && balanced(l) {
		lv, err := eval(l)
		if err != nil {
			return 0, err
		}
		rv, err := eval(r)
		return lv << rv, err
	}
	if strings.HasPrefix(expr, "-") {
		v, err := eval(expr[1:])
		return -v, err
	}
	expr = strings.TrimRight(expr, "uUlL")
	if len(expr) > 1 && expr[0] == '0' && expr[1] != 'x' && expr[1] != 'X' {
		return strconv.ParseInt(expr[1:], 8, 64)
	}
	return strconv.ParseInt(expr, 0, 64)
}

func balanced(s string) bool {
	depth := 0
	for _, c := range s {
		switch c {
		case '(':
			depth++
		case ')':
			depth--
			if depth < 0 {
				return false
			}
		}
	}
	return depth == 0
}

func splitTop(s string, sep rune) []string {
	var parts []string
	depth, start := 0, 0
	for i, c := range s {
		switch c {
		case '(':
			depth++
		case ')':
			depth--
		case sep:
			if depth == 0 {
				parts = append(parts, s[start:i])
				start = i + 1
			}
		}
	}
	return append(parts, s[start:])
}
