// Command genmodules generates the table of statically linked Postgres
// loadable modules that libpgzero's dlopen()/dlsym() consult.
//
// Usage: genmodules -o modules.c <module>.so.p ...
//
// Each argument is a meson object directory of a loadable module; the
// module's name is the directory name without ".so.p". Every global symbol
// the module's objects define is listed, with the per-module renaming done
// by wasm/toolchain/clang (pgzero_mod__<module>__<sym>) undone, so that
// dlsym(handle, "_PG_init") finds the right module's function.
//
// Functions are declared with prototypes matching their exact wasm
// signatures: wasm-ld replaces a reference through a mismatched signature
// with a trapping stub, so a generic void(void) declaration would not do.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/partite-ai/pgzero/wasm/internal/wasmobj"
)

func main() {
	out := flag.String("o", "", "output C file")
	flag.Parse()
	if *out == "" {
		log.Fatal("-o is required")
	}

	var mods []module
	for _, dir := range flag.Args() {
		m, err := readModule(dir)
		if err != nil {
			log.Fatalf("%s: %v", dir, err)
		}
		mods = append(mods, m)
	}
	sort.Slice(mods, func(i, j int) bool { return mods[i].name < mods[j].name })

	var b bytes.Buffer
	b.WriteString("/* Code generated by wasm/cmd/genmodules. DO NOT EDIT. */\n\n")
	b.WriteString("#include <stdint.h>\n\n#include \"pgzero.h\"\n\n")
	for _, m := range mods {
		fmt.Fprintf(&b, "/* %s */\n", m.name)
		for _, s := range m.syms {
			if s.fn != nil {
				fmt.Fprintf(&b, "extern %s %s(%s);\n", cResult(s.fn), s.link, cParams(s.fn))
			} else {
				fmt.Fprintf(&b, "extern char %s[];\n", s.link)
			}
		}
		fmt.Fprintf(&b, "static const pgzero_module_symbol syms_%s[] = {\n", m.ident)
		for _, s := range m.syms {
			fmt.Fprintf(&b, "\t{\"%s\", (void *) %s},\n", s.name, s.link)
		}
		b.WriteString("\t{0, 0}\n};\n\n")
	}
	b.WriteString("const pgzero_module pgzero_modules[] = {\n")
	for _, m := range mods {
		fmt.Fprintf(&b, "\t{\"%s\", syms_%s},\n", m.name, m.ident)
	}
	b.WriteString("\t{0, 0}\n};\n")
	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		log.Fatal(err)
	}
}

type module struct {
	name  string // as dlopen()ed: the file name without .so
	ident string // C identifier form
	syms  []symbol
}

type symbol struct {
	name string           // as dlsym()ed
	link string           // the linker's name for it
	fn   *wasmobj.FuncSig // nil for data
}

func ident(s string) string {
	return strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			return r
		}
		return '_'
	}, s)
}

func readModule(dir string) (module, error) {
	base := filepath.Base(strings.TrimSuffix(dir, "/"))
	if !strings.HasSuffix(base, ".so.p") {
		return module{}, errors.New("not a <module>.so.p directory")
	}
	name := strings.TrimSuffix(base, ".so.p")
	m := module{name: name, ident: ident(name)}
	prefix := "pgzero_mod__" + ident(name) + "__"

	objs, err := filepath.Glob(filepath.Join(dir, "*.o"))
	if err != nil {
		return m, err
	}
	seen := map[string]bool{}
	for _, o := range objs {
		syms, err := objectSymbols(o)
		if err != nil {
			return m, fmt.Errorf("%s: %w", o, err)
		}
		for _, s := range syms {
			if seen[s.link] {
				continue
			}
			seen[s.link] = true
			s.name = strings.TrimPrefix(s.link, prefix)
			m.syms = append(m.syms, s)
		}
	}
	sort.Slice(m.syms, func(i, j int) bool { return m.syms[i].link < m.syms[j].link })
	return m, nil
}

func ctype(t byte) string {
	switch t {
	case 0x7f:
		return "int32_t"
	case 0x7e:
		return "int64_t"
	case 0x7d:
		return "float"
	case 0x7c:
		return "double"
	}
	return "int32_t" // references don't occur in C code
}

func cResult(f *wasmobj.FuncSig) string {
	switch len(f.Results) {
	case 0:
		return "void"
	case 1:
		return ctype(f.Results[0])
	}
	return "void" // multi-value results don't occur in C code
}

func cParams(f *wasmobj.FuncSig) string {
	if len(f.Params) == 0 {
		return "void"
	}
	ps := make([]string, len(f.Params))
	for i, p := range f.Params {
		ps[i] = ctype(p)
	}
	return strings.Join(ps, ", ")
}

// objectSymbols returns the global, defined function and data symbols of
// a relocatable wasm object.
func objectSymbols(path string) ([]symbol, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	all, err := wasmobj.Symbols(data)
	if err != nil {
		return nil, err
	}
	var syms []symbol
	for _, s := range all {
		if !s.Defined() || s.Local() {
			continue
		}
		switch s.Kind {
		case wasmobj.KindFunction:
			syms = append(syms, symbol{link: s.Name, fn: s.Func})
		case wasmobj.KindData:
			syms = append(syms, symbol{link: s.Name})
		}
	}
	return syms, nil
}
