// Package assets embeds the Postgres build pgzero runs. The files are
// generated by `make embed` and committed, so that the module builds with a
// plain `go get`.
//
// Everything is gzipped; package pgzero decompresses it once per process.
package assets

import _ "embed"

// Postgres is the postgres program: a wasm32-wasip2 component.
//
//go:embed postgres.wasm.gz
var Postgres []byte

// Initdb is the initdb program: a wasm32-wasip2 component.
//
//go:embed initdb.wasm.gz
var Initdb []byte

// Install is a tar of the parts of the Postgres installation the server
// reads at runtime (share/, lib/), mounted at its install prefix.
//
//go:embed install.tar.gz
var Install []byte

// Template is a tar of a freshly initialized database cluster (UTF8, C
// locale, superuser "postgres", trust authentication), used instead of
// running initdb for every new cluster.
//
//go:embed template.tar.gz
var Template []byte
