// Code generated by wasm/cmd/genabi from wasi-libc headers. DO NOT EDIT.

package abi

// errno values
const (
	EPERM           = 63
	ENOENT          = 44
	ESRCH           = 71
	EINTR           = 27
	EIO             = 29
	EBADF           = 8
	ECHILD          = 12
	EAGAIN          = 6
	ENOMEM          = 48
	EACCES          = 2
	EFAULT          = 21
	EEXIST          = 20
	ENOTDIR         = 54
	EISDIR          = 31
	EINVAL          = 28
	ENFILE          = 41
	EMFILE          = 33
	ENOSPC          = 51
	ESPIPE          = 70
	EPIPE           = 64
	ERANGE          = 68
	ENOSYS          = 52
	ENOTSOCK        = 57
	EDESTADDRREQ    = 17
	EMSGSIZE        = 35
	EPROTOTYPE      = 67
	ENOPROTOOPT     = 50
	EPROTONOSUPPORT = 66
	EOPNOTSUPP      = 58
	EAFNOSUPPORT    = 5
	EADDRINUSE      = 3
	EADDRNOTAVAIL   = 4
	ENETDOWN        = 38
	ENETUNREACH     = 40
	ECONNABORTED    = 13
	ECONNRESET      = 15
	ENOBUFS         = 42
	EISCONN         = 30
	ENOTCONN        = 53
	ETIMEDOUT       = 73
	ECONNREFUSED    = 14
	EHOSTUNREACH    = 23
	EALREADY        = 7
	EINPROGRESS     = 26
)

// poll events
const (
	POLLIN     = 1
	POLLOUT    = 2
	POLLERR    = 4096
	POLLHUP    = 8192
	POLLNVAL   = 16384
	POLLPRI    = 512
	POLLRDNORM = 1
	POLLWRNORM = 2
)

// socket domains, types and flags
const (
	AF_UNSPEC     = 0
	AF_INET       = 1
	AF_INET6      = 2
	AF_UNIX       = 3
	SOCK_STREAM   = 6
	SOCK_DGRAM    = 5
	SOCK_NONBLOCK = 16384
	SOCK_CLOEXEC  = 8192
	SHUT_RD       = 1
	SHUT_WR       = 2
	SHUT_RDWR     = 3
	MSG_PEEK      = 2
	MSG_DONTWAIT  = 64
	MSG_NOSIGNAL  = 16384
)

// socket options
const (
	SOL_SOCKET    = 2147483647
	SO_REUSEADDR  = 2
	SO_KEEPALIVE  = 9
	SO_ERROR      = 4
	SO_RCVBUF     = 8
	SO_SNDBUF     = 7
	SO_TYPE       = 3
	IPPROTO_TCP   = 6
	IPPROTO_IPV6  = 41
	IPV6_V6ONLY   = 26
	TCP_NODELAY   = 1
	TCP_KEEPIDLE  = 4
	TCP_KEEPINTVL = 5
	TCP_KEEPCNT   = 6
)

// Not defined by wasi-libc: SO_LINGER

// fcntl
const (
	O_CREAT         = 4096
	O_EXCL          = 16384
	O_TRUNC         = 32768
	O_RDWR          = 335544320
	O_NONBLOCK      = 4
	O_CLOEXEC       = 0
	F_GETFD         = 1
	F_SETFD         = 2
	F_GETFL         = 3
	F_SETFL         = 4
	F_DUPFD         = 5
	F_DUPFD_CLOEXEC = 6
	FD_CLOEXEC      = 1
)

// signals
const (
	SIGHUP    = 1
	SIGINT    = 2
	SIGQUIT   = 3
	SIGILL    = 4
	SIGTRAP   = 5
	SIGABRT   = 6
	SIGBUS    = 7
	SIGFPE    = 8
	SIGKILL   = 9
	SIGUSR1   = 10
	SIGSEGV   = 11
	SIGUSR2   = 12
	SIGPIPE   = 13
	SIGALRM   = 14
	SIGTERM   = 15
	SIGCHLD   = 17
	SIGCONT   = 18
	SIGSTOP   = 19
	SIGTSTP   = 20
	SIGTTIN   = 21
	SIGTTOU   = 22
	SIGURG    = 23
	SIGXCPU   = 24
	SIGXFSZ   = 25
	SIGVTALRM = 26
	SIGPROF   = 27
	SIGWINCH  = 28
	SIGIO     = 29
	SIGSYS    = 31
	NSIG      = 65
)

// wait
const (
	WNOHANG = 1
)
